// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.5.0.14890
//    <NameSpace>Modulo.Collect.OVAL.SystemCharacteristics.Ios</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings>Modulo.Collect.OVAL.Common;Modulo.Collect.OVAL.SystemCharacteristics</CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Modulo.Collect.OVAL.SystemCharacteristics.Ios {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using Modulo.Collect.OVAL.Common;
    using Modulo.Collect.OVAL.SystemCharacteristics;
    
    
    /// <summary>
    /// Sotres information about the existence of a particular line in the ios config file under the global context
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.5.0.14895")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios", IsNullable=false)]
    public partial class global_item : ItemType {
        
        private EntityItemStringType global_commandField;
        
        public EntityItemStringType global_command {
            get {
                return this.global_commandField;
            }
            set {
                this.global_commandField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.5.0.14895")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios", IsNullable=false)]
    public partial class interface_item : ItemType {
        
        private EntityItemStringType nameField;
        
        private EntityItemStringType ip_directed_broadcast_commandField;
        
        private EntityItemStringType no_ip_directed_broadcast_commandField;
        
        private EntityItemStringType proxy_arp_commandField;
        
        private EntityItemStringType shutdown_commandField;
        
        public EntityItemStringType name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        public EntityItemStringType ip_directed_broadcast_command {
            get {
                return this.ip_directed_broadcast_commandField;
            }
            set {
                this.ip_directed_broadcast_commandField = value;
            }
        }
        
        public EntityItemStringType no_ip_directed_broadcast_command {
            get {
                return this.no_ip_directed_broadcast_commandField;
            }
            set {
                this.no_ip_directed_broadcast_commandField = value;
            }
        }
        
        public EntityItemStringType proxy_arp_command {
            get {
                return this.proxy_arp_commandField;
            }
            set {
                this.proxy_arp_commandField = value;
            }
        }
        
        public EntityItemStringType shutdown_command {
            get {
                return this.shutdown_commandField;
            }
            set {
                this.shutdown_commandField = value;
            }
        }
    }
    
    /// <summary>
    /// Stores the properties of specific lines in the ios config file.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.5.0.14895")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios", IsNullable=false)]
    public partial class line_item : ItemType {
        
        private EntityItemStringType show_subcommandField;
        
        private EntityItemStringType config_lineField;
        
        /// <summary>
        /// The name of the SHOW sub-command.
        /// </summary>
        public EntityItemStringType show_subcommand {
            get {
                return this.show_subcommandField;
            }
            set {
                this.show_subcommandField = value;
            }
        }
        
        /// <summary>
        /// The value returned from by the specified SHOW sub-command.
        /// </summary>
        public EntityItemStringType config_line {
            get {
                return this.config_lineField;
            }
            set {
                this.config_lineField = value;
            }
        }
    }
    
    /// <summary>
    /// Stores results from collecting lines under the global context associated with snmp.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.5.0.14895")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios", IsNullable=false)]
    public partial class snmp_item : ItemType {
        
        private EntityItemStringType access_listField;
        
        private EntityItemStringType community_nameField;
        
        public EntityItemStringType access_list {
            get {
                return this.access_listField;
            }
            set {
                this.access_listField = value;
            }
        }
        
        public EntityItemStringType community_name {
            get {
                return this.community_nameField;
            }
            set {
                this.community_nameField = value;
            }
        }
    }
    
    /// <summary>
    /// The tclsh item holds information about the availability of tcl on the IOS operating system. It extends the standard ItemType as defined in the oval-system-characteristics schema and one should refer to the ItemType description for more information.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.5.0.14895")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios", IsNullable=false)]
    public partial class tclsh_item : ItemType {
        
        private EntityItemBoolType availableField;
        
        /// <summary>
        /// This boolean entity describes whether TCLSH is available on the system. A value of true means that TCLSH is available. Per Cisco documentation, the accepted way to see if the device supports tcl functionality is to enter the tcl shell. If the attempt results in a tcl prompt then the device supports tclsh and has it enabled.
        /// </summary>
        public EntityItemBoolType available {
            get {
                return this.availableField;
            }
            set {
                this.availableField = value;
            }
        }
    }
    
    /// <summary>
    /// The version_item holds information about the version of the IOS operating system. It extends the standard ItemType as defined in the oval-system-characteristics schema and one should refer to the ItemType description for more information.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.5.0.14895")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios", IsNullable=false)]
    public partial class version_item : ItemType {
        
        private EntityItemStringType major_releaseField;
        
        private EntityItemStringType train_numberField;
        
        private EntityItemIntType major_versionField;
        
        private EntityItemIntType minor_versionField;
        
        private EntityItemIntType releaseField;
        
        private EntityItemStringType train_identifierField;
        
        private EntityItemIntType rebuildField;
        
        private EntityItemStringType subrebuildField;
        
        private EntityItemStringType mainline_rebuildField;
        
        private EntityItemIOSVersionType version_stringField;
        
        /// <summary>
        /// The major_release is a combination of train and rebuild information and is used by Cisco advisories to identify major releases.
        /// </summary>
        public EntityItemStringType major_release {
            get {
                return this.major_releaseField;
            }
            set {
                this.major_releaseField = value;
            }
        }
        
        /// <summary>
        /// The train number is the dotted version that starts a version string. For example the version string 12.2(3)T has a train number of 12.2.
        /// </summary>
        public EntityItemStringType train_number {
            get {
                return this.train_numberField;
            }
            set {
                this.train_numberField = value;
            }
        }
        
        /// <summary>
        /// The major_version entity specifies the major version piece of the version string.  The value is an integer and in the example 12.4(9)T0a the major version is '12'.
        /// </summary>
        public EntityItemIntType major_version {
            get {
                return this.major_versionField;
            }
            set {
                this.major_versionField = value;
            }
        }
        
        /// <summary>
        /// The minor_version entity specifies the minor version piece of the version string.  The value is an integer and in the example 12.4(9)T0a the minor version is '4'.
        /// </summary>
        public EntityItemIntType minor_version {
            get {
                return this.minor_versionField;
            }
            set {
                this.minor_versionField = value;
            }
        }
        
        /// <summary>
        /// The release entity specifies the release piece of the version string.  The value is an integer and in the example 12.4(9)T0a the release is '9'.
        /// </summary>
        public EntityItemIntType release {
            get {
                return this.releaseField;
            }
            set {
                this.releaseField = value;
            }
        }
        
        /// <summary>
        /// The train_identifier entity specifies the type of train represented in the version string.  The value is a string and in the example 12.4(9)T0a the train identifier is 'T'.  The following explaination from Wikipedia should help explain the different train identifiers. Cisco IOS releases are split into several "trains", each containing a different set of features. Trains more or less map onto distinct markets or groups of customers that Cisco is targeting.  The 'mainline' train is designed to be the most stable release the company can offer, and its feature set never expands during its lifetime. Updates are released only to address bugs in the product. The previous technology train becomes the source for the current mainline train--for example, the 12.1T train becomes the basis for the 12.2 mainline. Therefore, to determine the features available in a particular mainline release, look at the previous T train release.  The 'T' (Technology) train, gets new features and bug fixes throughout its life, and is therefore less stable than the mainline. (In releases prior to Cisco IOS Release 12.0, the P train served as the Technology train.)  The 'S' (Service Provider) train, runs only on the company's core router products and is heavily customized for Service Provider customers.  The 'E' (Enterprise) train, is customized for implementation in enterprise environments.  The 'B' (broadband) train, support internet based broadband features.  The 'XA', 'Xb' ... (special functionality) train, needs to be documented.  There are other trains from time to time, designed for specific needs -- for example, the 12.0AA train contained new code required for Cisco's AS5800 product.
        /// </summary>
        public EntityItemStringType train_identifier {
            get {
                return this.train_identifierField;
            }
            set {
                this.train_identifierField = value;
            }
        }
        
        /// <summary>
        /// The rebuild entity specifies the rebuild piece of the version string  The value is an integer and in the example 12.4(9)T0a the rebuild is '0'.  Often a rebuild is compiled to fix a single specific problem or vulnerability for a given IOS version. For example, 12.1(8)E14 is a Rebuild, the 14 denoting the 14th rebuild of 12.1(8)E. Rebuilds are produced to either quickly repair a defect, or to satisfy customers who do not want to upgrade to a later major revision because they may be running critical infrastructure on their devices, and hence prefer to minimise change and risk.
        /// </summary>
        public EntityItemIntType rebuild {
            get {
                return this.rebuildField;
            }
            set {
                this.rebuildField = value;
            }
        }
        
        /// <summary>
        /// The subrebuild entity specifies the subrebuild piece of the version string.  The value is a string and in the example 12.4(9)T0a the subrebuild is 'a'.
        /// </summary>
        public EntityItemStringType subrebuild {
            get {
                return this.subrebuildField;
            }
            set {
                this.subrebuildField = value;
            }
        }
        
        /// <summary>
        /// The mainline_rebuild entity specifies the mainline rebuild piece of the version string.  The mainline rebuild is just a regular rebuild release against the mainline operating system release (e.g. the branch of development that would typically be called "the trunk" that isn't associated with a train). Since there is no train identifier to stick the rebuild release after, they stick a alphabetic character inside the parens holding the maintenance release number. For example, 12.4(5b) is the second rebuild of the 12.4(5) maintenance release.
        /// </summary>
        public EntityItemStringType mainline_rebuild {
            get {
                return this.mainline_rebuildField;
            }
            set {
                this.mainline_rebuildField = value;
            }
        }
        
        /// <summary>
        /// The version entity holds the raw string output of a 'show version' command.
        /// </summary>
        public EntityItemIOSVersionType version_string {
            get {
                return this.version_stringField;
            }
            set {
                this.version_stringField = value;
            }
        }
    }
}
