//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modulo.Collect.Probe.Xtet.CodeControlWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.model.codecontrol.com", ConfigurationName="CodeControlWS.ScanWS")]
    public interface ScanWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EvidenceDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="scanIssueListBySystemReturn")]
        Modulo.Collect.Probe.Xtet.CodeControlWS.ScanResultDTO scanIssueListBySystem(string token, long systemId, long[] issueList);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EvidenceDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="findScanReturn")]
        ScanResultDTO[] findScan(string token, Modulo.Collect.Probe.Xtet.CodeControlWS.ScanCriteriaDTO scanCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EvidenceDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="authenticateReturn")]
        Modulo.Collect.Probe.Xtet.CodeControlWS.AuthenticationDTO authenticate(string login, string password);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://dto.webservice.model.codecontrol.com")]
    public partial class ScanResultDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EvidenceDTO[] evidenceListField;
        
        private bool hasIssuesField;
        
        private bool internalErrorField;
        
        private string internalErrorMessageField;
        
        private string parentRequestField;
        
        private System.Nullable<decimal> riskLevelField;
        
        private System.Nullable<long> scanIdField;
        
        private string statusField;
        
        private System.Nullable<long> systemIdField;
        
        private string systemTypeField;
        
        private System.Nullable<long> totalIssuesFoundField;
        
        private System.Nullable<long> totalProgramsScannedField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public EvidenceDTO[] evidenceList {
            get {
                return this.evidenceListField;
            }
            set {
                this.evidenceListField = value;
                this.RaisePropertyChanged("evidenceList");
            }
        }
        
        /// <remarks/>
        public bool hasIssues {
            get {
                return this.hasIssuesField;
            }
            set {
                this.hasIssuesField = value;
                this.RaisePropertyChanged("hasIssues");
            }
        }
        
        /// <remarks/>
        public bool internalError {
            get {
                return this.internalErrorField;
            }
            set {
                this.internalErrorField = value;
                this.RaisePropertyChanged("internalError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string internalErrorMessage {
            get {
                return this.internalErrorMessageField;
            }
            set {
                this.internalErrorMessageField = value;
                this.RaisePropertyChanged("internalErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string parentRequest {
            get {
                return this.parentRequestField;
            }
            set {
                this.parentRequestField = value;
                this.RaisePropertyChanged("parentRequest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> riskLevel {
            get {
                return this.riskLevelField;
            }
            set {
                this.riskLevelField = value;
                this.RaisePropertyChanged("riskLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<long> scanId {
            get {
                return this.scanIdField;
            }
            set {
                this.scanIdField = value;
                this.RaisePropertyChanged("scanId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<long> systemId {
            get {
                return this.systemIdField;
            }
            set {
                this.systemIdField = value;
                this.RaisePropertyChanged("systemId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string systemType {
            get {
                return this.systemTypeField;
            }
            set {
                this.systemTypeField = value;
                this.RaisePropertyChanged("systemType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<long> totalIssuesFound {
            get {
                return this.totalIssuesFoundField;
            }
            set {
                this.totalIssuesFoundField = value;
                this.RaisePropertyChanged("totalIssuesFound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<long> totalProgramsScanned {
            get {
                return this.totalProgramsScannedField;
            }
            set {
                this.totalProgramsScannedField = value;
                this.RaisePropertyChanged("totalProgramsScanned");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://dto.webservice.model.codecontrol.com")]
    public partial class EvidenceDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string detailsField;
        
        private System.Nullable<long> issueIdField;
        
        private string issueTypeField;
        
        private System.Nullable<long> lineNumberField;
        
        private string programNameField;
        
        private string requestField;
        
        private System.Nullable<decimal> riskLevelField;
        
        private string sapModuleField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
                this.RaisePropertyChanged("details");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<long> issueId {
            get {
                return this.issueIdField;
            }
            set {
                this.issueIdField = value;
                this.RaisePropertyChanged("issueId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string issueType {
            get {
                return this.issueTypeField;
            }
            set {
                this.issueTypeField = value;
                this.RaisePropertyChanged("issueType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<long> lineNumber {
            get {
                return this.lineNumberField;
            }
            set {
                this.lineNumberField = value;
                this.RaisePropertyChanged("lineNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string programName {
            get {
                return this.programNameField;
            }
            set {
                this.programNameField = value;
                this.RaisePropertyChanged("programName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
                this.RaisePropertyChanged("request");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> riskLevel {
            get {
                return this.riskLevelField;
            }
            set {
                this.riskLevelField = value;
                this.RaisePropertyChanged("riskLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sapModule {
            get {
                return this.sapModuleField;
            }
            set {
                this.sapModuleField = value;
                this.RaisePropertyChanged("sapModule");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://dto.webservice.model.codecontrol.com")]
    public partial class AuthenticationDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool errorField;
        
        private string errorMessageField;
        
        private string tokenField;
        
        /// <remarks/>
        public bool error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://dto.webservice.model.codecontrol.com")]
    public partial class ScanCriteriaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<System.DateTime> endExecutionDateField;
        
        private System.Nullable<bool> hasIssuesField;
        
        private long[] issueIdListField;
        
        private System.Nullable<bool> onlyRequestsField;
        
        private string[] programListField;
        
        private string[] requestListField;
        
        private long[] scanIdListField;
        
        private System.Nullable<System.DateTime> startExecutionDateField;
        
        private long[] systemIdListField;
        
        private System.Nullable<long> verifySinceScanIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> endExecutionDate {
            get {
                return this.endExecutionDateField;
            }
            set {
                this.endExecutionDateField = value;
                this.RaisePropertyChanged("endExecutionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<bool> hasIssues {
            get {
                return this.hasIssuesField;
            }
            set {
                this.hasIssuesField = value;
                this.RaisePropertyChanged("hasIssues");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public long[] issueIdList {
            get {
                return this.issueIdListField;
            }
            set {
                this.issueIdListField = value;
                this.RaisePropertyChanged("issueIdList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<bool> onlyRequests {
            get {
                return this.onlyRequestsField;
            }
            set {
                this.onlyRequestsField = value;
                this.RaisePropertyChanged("onlyRequests");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string[] programList {
            get {
                return this.programListField;
            }
            set {
                this.programListField = value;
                this.RaisePropertyChanged("programList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string[] requestList {
            get {
                return this.requestListField;
            }
            set {
                this.requestListField = value;
                this.RaisePropertyChanged("requestList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public long[] scanIdList {
            get {
                return this.scanIdListField;
            }
            set {
                this.scanIdListField = value;
                this.RaisePropertyChanged("scanIdList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> startExecutionDate {
            get {
                return this.startExecutionDateField;
            }
            set {
                this.startExecutionDateField = value;
                this.RaisePropertyChanged("startExecutionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public long[] systemIdList {
            get {
                return this.systemIdListField;
            }
            set {
                this.systemIdListField = value;
                this.RaisePropertyChanged("systemIdList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<long> verifySinceScanId {
            get {
                return this.verifySinceScanIdField;
            }
            set {
                this.verifySinceScanIdField = value;
                this.RaisePropertyChanged("verifySinceScanId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ScanWSChannel : Modulo.Collect.Probe.Xtet.CodeControlWS.ScanWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScanWSClient : System.ServiceModel.ClientBase<Modulo.Collect.Probe.Xtet.CodeControlWS.ScanWS>, Modulo.Collect.Probe.Xtet.CodeControlWS.ScanWS {
        
        public ScanWSClient() {
        }
        
        public ScanWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScanWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScanWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScanWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Modulo.Collect.Probe.Xtet.CodeControlWS.ScanResultDTO scanIssueListBySystem(string token, long systemId, long[] issueList) {
            return base.Channel.scanIssueListBySystem(token, systemId, issueList);
        }
        
        public ScanResultDTO[] findScan(string token, Modulo.Collect.Probe.Xtet.CodeControlWS.ScanCriteriaDTO scanCriteria) {
            return base.Channel.findScan(token, scanCriteria);
        }
        
        public Modulo.Collect.Probe.Xtet.CodeControlWS.AuthenticationDTO authenticate(string login, string password) {
            return base.Channel.authenticate(login, password);
        }
    }
}
