//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modulo.Collect.GraphicalConsole {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Modulo.Collect.GraphicalConsole.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read from file.
        /// </summary>
        public static string CannotReadFromFile {
            get {
                return ResourceManager.GetString("CannotReadFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting data on {0}..
        /// </summary>
        public static string CollectingData {
            get {
                return ResourceManager.GetString("CollectingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection has finished..
        /// </summary>
        public static string CollectionFinished {
            get {
                return ResourceManager.GetString("CollectionFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty definition file name..
        /// </summary>
        public static string EmptyDefinitionFilename {
            get {
                return ResourceManager.GetString("EmptyDefinitionFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty destination folder name..
        /// </summary>
        public static string EmptyDestinationFolderName {
            get {
                return ResourceManager.GetString("EmptyDestinationFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty OVAL Results file returned from modSIC..
        /// </summary>
        public static string EmptyOVALResults {
            get {
                return ResourceManager.GetString("EmptyOVALResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to get System Characteristics from OVAL Results document..
        /// </summary>
        public static string ImpossibleToGetSystemCharacteristics {
            get {
                return ResourceManager.GetString("ImpossibleToGetSystemCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Exception:.
        /// </summary>
        public static string InnerException {
            get {
                return ResourceManager.GetString("InnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration..
        /// </summary>
        public static string InvalidConfiguration {
            get {
                return ResourceManager.GetString("InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid modSIC server configuration..
        /// </summary>
        public static string InvalidServerConfiguration {
            get {
                return ResourceManager.GetString("InvalidServerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid target configuration..
        /// </summary>
        public static string InvalidTargetConfiguration {
            get {
                return ResourceManager.GetString("InvalidTargetConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVAL Definitions file not found..
        /// </summary>
        public static string OVALDefinitionsFileNotFound {
            get {
                return ResourceManager.GetString("OVALDefinitionsFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVAL Definitions (*.xml)|*.xml.
        /// </summary>
        public static string OVALDefinitionsFilter {
            get {
                return ResourceManager.GetString("OVALDefinitionsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OVAL Results document was saved..
        /// </summary>
        public static string OVALResultsDocumentWasSaved {
            get {
                return ResourceManager.GetString("OVALResultsDocumentWasSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OVAL System Characteristics document was saved..
        /// </summary>
        public static string OVALSystemCharacteristicsDocumentWasSaved {
            get {
                return ResourceManager.GetString("OVALSystemCharacteristicsDocumentWasSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting a collection..
        /// </summary>
        public static string RequestingCollection {
            get {
                return ResourceManager.GetString("RequestingCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema validation failure..
        /// </summary>
        public static string SchemaValidationFailure {
            get {
                return ResourceManager.GetString("SchemaValidationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder to Save Results.
        /// </summary>
        public static string SelectFolderToSaveResults {
            get {
                return ResourceManager.GetString("SelectFolderToSaveResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select OVAL Definitions File.
        /// </summary>
        public static string SelectOVALDefinitionsFile {
            get {
                return ResourceManager.GetString("SelectOVALDefinitionsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modSIC server generated an ID for this collection: {0}..
        /// </summary>
        public static string ServerGeneratedID {
            get {
                return ResourceManager.GetString("ServerGeneratedID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH Port:.
        /// </summary>
        public static string SSHPort {
            get {
                return ResourceManager.GetString("SSHPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to fetch OVAL documents..
        /// </summary>
        public static string TryingFetchOVALDocuments {
            get {
                return ResourceManager.GetString("TryingFetchOVALDocuments", resourceCulture);
            }
        }
    }
}
