//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace modSICTest
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DatabaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DatabaseEntities object using the connection string found in the 'DatabaseEntities' section of the application configuration file.
        /// </summary>
        public DatabaseEntities() : base("name=DatabaseEntities", "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatabaseEntities object.
        /// </summary>
        public DatabaseEntities(string connectionString) : base(connectionString, "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatabaseEntities object.
        /// </summary>
        public DatabaseEntities(EntityConnection connection) : base(connection, "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Execution> Executions
        {
            get
            {
                if ((_Executions == null))
                {
                    _Executions = base.CreateObjectSet<Execution>("Executions");
                }
                return _Executions;
            }
        }
        private ObjectSet<Execution> _Executions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OvalDefinition> OvalDefinitions
        {
            get
            {
                if ((_OvalDefinitions == null))
                {
                    _OvalDefinitions = base.CreateObjectSet<OvalDefinition>("OvalDefinitions");
                }
                return _OvalDefinitions;
            }
        }
        private ObjectSet<OvalDefinition> _OvalDefinitions;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Executions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToExecutions(Execution execution)
        {
            base.AddObject("Executions", execution);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OvalDefinitions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOvalDefinitions(OvalDefinition ovalDefinition)
        {
            base.AddObject("OvalDefinitions", ovalDefinition);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Execution")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Execution : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Execution object.
        /// </summary>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="idDefinition">Initial value of the IdDefinition property.</param>
        public static Execution CreateExecution(global::System.DateTime date, global::System.Int32 idDefinition)
        {
            Execution execution = new Execution();
            execution.Date = date;
            execution.IdDefinition = idDefinition;
            return execution;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                if (_Date != value)
                {
                    OnDateChanging(value);
                    ReportPropertyChanging("Date");
                    _Date = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Date");
                    OnDateChanged();
                }
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdDefinition
        {
            get
            {
                return _IdDefinition;
            }
            set
            {
                if (_IdDefinition != value)
                {
                    OnIdDefinitionChanging(value);
                    ReportPropertyChanging("IdDefinition");
                    _IdDefinition = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdDefinition");
                    OnIdDefinitionChanged();
                }
            }
        }
        private global::System.Int32 _IdDefinition;
        partial void OnIdDefinitionChanging(global::System.Int32 value);
        partial void OnIdDefinitionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NTrue
        {
            get
            {
                return _NTrue;
            }
            set
            {
                OnNTrueChanging(value);
                ReportPropertyChanging("NTrue");
                _NTrue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NTrue");
                OnNTrueChanged();
            }
        }
        private Nullable<global::System.Int32> _NTrue;
        partial void OnNTrueChanging(Nullable<global::System.Int32> value);
        partial void OnNTrueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NFalse
        {
            get
            {
                return _NFalse;
            }
            set
            {
                OnNFalseChanging(value);
                ReportPropertyChanging("NFalse");
                _NFalse = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NFalse");
                OnNFalseChanged();
            }
        }
        private Nullable<global::System.Int32> _NFalse;
        partial void OnNFalseChanging(Nullable<global::System.Int32> value);
        partial void OnNFalseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NError
        {
            get
            {
                return _NError;
            }
            set
            {
                OnNErrorChanging(value);
                ReportPropertyChanging("NError");
                _NError = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NError");
                OnNErrorChanged();
            }
        }
        private Nullable<global::System.Int32> _NError;
        partial void OnNErrorChanging(Nullable<global::System.Int32> value);
        partial void OnNErrorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NUnknown
        {
            get
            {
                return _NUnknown;
            }
            set
            {
                OnNUnknownChanging(value);
                ReportPropertyChanging("NUnknown");
                _NUnknown = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NUnknown");
                OnNUnknownChanged();
            }
        }
        private Nullable<global::System.Int32> _NUnknown;
        partial void OnNUnknownChanging(Nullable<global::System.Int32> value);
        partial void OnNUnknownChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Duration
        {
            get
            {
                return _Duration;
            }
            set
            {
                OnDurationChanging(value);
                ReportPropertyChanging("Duration");
                _Duration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Duration");
                OnDurationChanged();
            }
        }
        private Nullable<global::System.Int64> _Duration;
        partial void OnDurationChanging(Nullable<global::System.Int64> value);
        partial void OnDurationChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="OvalDefinition")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OvalDefinition : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OvalDefinition object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static OvalDefinition CreateOvalDefinition(global::System.Int32 id)
        {
            OvalDefinition ovalDefinition = new OvalDefinition();
            ovalDefinition.Id = id;
            return ovalDefinition;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Filename
        {
            get
            {
                return _Filename;
            }
            set
            {
                OnFilenameChanging(value);
                ReportPropertyChanging("Filename");
                _Filename = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Filename");
                OnFilenameChanged();
            }
        }
        private global::System.String _Filename;
        partial void OnFilenameChanging(global::System.String value);
        partial void OnFilenameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Parameters
        {
            get
            {
                return _Parameters;
            }
            set
            {
                OnParametersChanging(value);
                ReportPropertyChanging("Parameters");
                _Parameters = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Parameters");
                OnParametersChanged();
            }
        }
        private global::System.String _Parameters;
        partial void OnParametersChanging(global::System.String value);
        partial void OnParametersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _Active;
        partial void OnActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnActiveChanged();

        #endregion
    
    }

    #endregion
    
}
